sudo: false
language: node_js
node_js:
- '10.0.0'
stages:
- test
jobs:
  include:
  - stage: test
    name: "Lint and Test"
    script:
    - yarn lint
    - yarn test
notifications:
  webhooks:
    secure: "fs+mP8sS1GNYhvCV7eFdDvli6zgai9+05fCDugTW0WXNl5FR6yUVZqmXAe6ptw5zPwyHvxggUUkb0n9uhS/EhSrnMaNVqgkt5uDHs6VGJLVUBA4jo9zy/aTRTgIGDkK3CAToiEi5Qs54hwGiLIPxslPGyUM1WowTN0BCg50GDOs43Fa17PwfWlQ+ZUVAuoWXR9yAaMPhHAtPyr3w5QydvIYwnwKXjMU+BOz5OQYMGC9nvPdsFFxQYiGFYnFVQoo7AkXZN8vJ5Q9FsLUNGaB1mtFr/SWbLgTslE21ZTqp7ZytL0Vb6lGscWwZ8KqJMrE45qlOn+sYsBuifhvBBGG0TI4zK98ii9rSQ3zmKlDxDkQXmFMc9vz5mwyzIPno0vL2zLsQNVuZA3i95fPHnUYqU6BpKUuC9biT9Ja215M4xSzxFIl/OVVI345RgV7E7Y94uhLoA3jRiJpH4toOiNVrOrLj3ib8LIkXpWvcn11ZqYz3VuQn/trX3ILsivZ3+zsIVYnMMXAPfk3IKnTnj8BajkzuQQM4IlqfqXyHYGOIufgFnB2ezbSPMB2dPlW/5rZaQ+MqQFPVUbZSxekGr+8P96QTtqZQBCMgOP8WbXc7Ml1rHAok+mPFes6hZge7LgnbqknMXc5u2WTLk32/I7Rp70GFl1t17TA/Qe4aiKTq51s="
